# Toml document to used for building model input
# datapackages

title = "Fuchur build config for scenario 1"
description = "Electricity sector for DE and DK."
name = "scenario2"

[owner]
name = "ZNES"

[raw-data]
path = "fuchur-raw-data"
download = true

[cost]
wacc = 0.07

[cost.factor]
pv = 1
lithium_battery = 1
acaes = 1

[temporal]
scenario_year = 2050
weather_year = 2012
demand_year = 2012

[potential]
wind = "LIMES-EU"
pv = "LIMES-EU"
biomass = "hotmaps"

[buses]

electricity = [
    "AT",
    "BE",
    "BG",
    "CH",
    "CZ",
    "DE",
    "ES",
    "FI",
    "FR",
    "HR",
    "HU",
    "IE",
    "IT",
    "LT",
    "LV",
    "MK",
    "NL",
    "NO",
    "PL",
    "PT",
    "RO",
    "SE",
    "SI",
    "SK",
    "GB"
]

biomass = [
    "AT",
    "BE",
    "BG",
    "CH",
    "CZ",
    "DE",
    "ES",
    "FI",
    "FR",
    "HR",
    "HU",
    "IE",
    "IT",
    "LT",
    "LV",
    "MK",
    "NL",
    "NO",
    "PL",
    "PT",
    "RO",
    "SE",
    "SI",
    "SK",
    "GB"
]

[buses.heat]

decentral = []
central = []

[technologies]

investment = [
  "wind_onshore",
  "wind_offshore",
  "pv",
  "ocgt",
  "ccgt",
  "acaes",
  "biomass",
  "lithium_battery",
  "coal"
]
